language: go
go:
- 1.1
- 1.2
- 1.3

before_install:
- wget http://apache.mirror.nexicom.net/kafka/0.8.1.1/kafka_2.10-0.8.1.1.tgz -O kafka.tgz
- mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
- nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
- sleep 5
- nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
