---
name: Fuzzing

on: [push, pull_request]

jobs:
  test:
    name: Fuzz
    runs-on: ubuntu-latest

    env:
      GOFLAGS: -trimpath

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Get Go environment
      id: go-env
      run: |
        echo "::set-output name=cache::$(go env GOCACHE)"
        echo "::set-output name=modcache::$(go env GOMODCACHE)"

    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.go-env.outputs.cache }}
          ${{ steps.go-env.outputs.modcache }}
        key: fuzz-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          fuzz-go-

    - name: Build Go tip
      run: go install golang.org/dl/gotip@latest && gotip download

    - name: Run any fuzzing tests
      run: gotip test -v -run=^Fuzz -test.fuzztime=5m ./...
