name: FVT
on:
  merge_group:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "**"
jobs:
  fvt:
    name: Test with Kafka ${{ matrix.kafka-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19.x]
        kafka-version: [3.3.2, 3.4.1, 3.5.1]
    env:
      DEBUG: true
      GOFLAGS: -trimpath
      KAFKA_VERSION: ${{ matrix.kafka-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Get Go environment
      id: go-env
      run: |
        echo "cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
        echo "modcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.go-env.outputs.cache }}
          ${{ steps.go-env.outputs.modcache }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Test (Functional)
      run: make test_functional
